development:
  adapter: postgresql
  encoding: unicode
  database: joahg_development
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: joahg_test
  pool: 5
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: joahg_production
  pool: 5
  username: joahg
  password:
